# Generated by Django 4.2.27 on 2026-01-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_daily_reward_at',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='crypto.rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='max_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
