# Generated by Django 6.0.1 on 2026-01-28 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_localwithdrawal_localdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdeposit',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localdeposit',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_local_deposits', to=settings.AUTH_USER_MODEL),
        ),
    ]
